title: Jakub Poćwiardowski
logo: /assets/img/round_profilowe.png
description: BE in Automatic Control and Robotics | MSc Student in Computer Science | Software Developer.
# show_downloads: true
theme: jekyll-theme-minimal
